### ISSUE TITLE
Add profile picture (Add default null value in DB)

### ISSUE THREAD

**Issue by micmac473** [micmac473/junktrade#1]
Add functionality to upload profile picture for the current user and display it in the header
If no profile picture is uploaded then default profile picture is logo

**Comment by micmac473** [comment]
Instead of using a function to set the default profile picture if a user doesn't have one, we can set the profile picture path as the default value in the database field

**Comment by MikMontoute** [comment]
i dont have separate functions for viewing default and actual profile pics. just if that field is NULL use that path else use the path which is in the record

if($pp == "null"){
return "<img src=../img/defaultPP.jpg style='width:100%; border-radius: 50px;' class='img-responsive img-thumbnail mx-auto'>";
 }
 else{
 return "<img src= $pp style='width:100%; border-radius: 50px;' class='img-responsive img-thumbnail mx-auto'>"; 
}

**Comment by MikMontoute** [comment]
the 2 functions that are there is one for the profile page and one for when a user profile is being viewed

**Comment by micmac473** [comment]
I got you. But I doh find the default one working because I don't see the picture if I don't upload an image. So to avoid that, we can just set the default value of `profilepicture` in the users table to `defaultPP.jpg` then when they upload a new picture it'll update. What you think? The function for the other user's profile is fine.

**Comment by MikMontoute** [comment]
lol it work trust me its just the DB have to REDO to reflect what we want..... Just make the profilepicture field nullable and default so once a record is made it will be set to null at first.... that is the null my function is looking for.. not null as in an empty field... null as in DB NULL

**Comment by micmac473** [comment]
Lol ohh okay. I got you now. Well that's an easy fix
