### ISSUE TITLE
On clicking image

### ISSUE THREAD

**Issue by micmac473** [micmac473/JunkTrade#28]
Display in a modal as opposed to displaying on a separate page

**Comment by micmac473** [comment]
When the user clicks the image, that counts as the views right?

**Comment by MikMontoute** [comment]
yes clicking the image count as a view.... putting it in a modal window ainit easy X|

**Comment by MikMontoute** [comment]
but i understand that since all pics different sizes it shows up the size on the page small or big

**Comment by micmac473** [comment]
Try it man lol. Yeah cause the images are of different sizes
